import type { Metadata } from "next";
import { Figtree, Playfair } from 'next/font/google';
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";
import "./globals.css";

const figtree = Figtree({
  subsets: ['latin'],
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  variable: '--font-figtree',
});

const playFair = Playfair({
  subsets: ['latin'],
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  variable: '--font-playfair',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${figtree.variable} ${playFair.variable} antialiased`}
      >
        <Header />
        <aside className="grid grid-cols-12">
          <div className="col-span-4 bg-[#C9bff2]">
          </div>
          <div className="col-span-8 bg-white py-4 px-6">
            {children}
          </div>
        </aside>
        <Footer />
      </body>
    </html>
  );
}
